class InstallSearchjoy < ActiveRecord::Migration
  def change
    create_table :searchjoy_searches do |t|
      t.text    :rails_session_id
      t.jsonb   :ui_session_data, default: {},   null: false

      #SearchJoy
      t.text      :search_type
      t.text      :query
      t.text      :normalized_query
      t.integer   :results_count
      t.timestamps index:true
      t.integer   :convertable_id
      t.text      :convertable_type
      t.timestamp :converted_at
    end

    add_index :searchjoy_searches, [:rails_session_id]
    # add_index :searchjoy_searches, [:created_at]
    add_index :searchjoy_searches, [:search_type, :created_at]
    add_index :searchjoy_searches, [:search_type, :normalized_query, :created_at], name: "index_searchjoy_searches_on_search_type_and_normalized_query_an" # autogenerated name is too long
    add_index :searchjoy_searches, [:convertable_id, :convertable_type]
  end
end
